# Generated by Django 4.1.4 on 2022-12-25 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etask', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewTaskForm',
        ),
    ]
